services:
  explorer-proxy:
    container_name: explorer-proxy
    build:
      context: ./proxy
      dockerfile: ../proxy/Dockerfile.proxy
    working_dir: /srv/proxy
    env_file:
      - .env
    environment:
      - DEV_MODE=true
    volumes:
      - type: bind
        source: ./proxy
        target: /srv/proxy
    networks:
      - invariant-explorer-web
    ports: []
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.explorer-proxy-api.rule=(Host(`localhost`) && PathPrefix(`/api/v1/proxy/`)) || (Host(`127.0.0.1`) && PathPrefix(`/api/v1/proxy/`))"
      - "traefik.http.routers.explorer-proxy-api.entrypoints=invariant-explorer-web"
      - "traefik.http.services.explorer-proxy-api.loadbalancer.server.port=8000"
      - "traefik.docker.network=invariant-explorer-web"

networks:
  invariant-explorer-web:
    external: true